package dev.menace.utils.security;

public class StringGrabber {

    public static String getString(int input) {
        switch (input) {
            case 0:
                return "";
            case 1:
                return "getName";
            case 2:
                return "render";
            case 3:
                return "getPosX";
            case 4:
                return "getPosY";
            case 5:
                return "getPosZ";
            case 6:
                return "isVisible";
            case 7:
                return "getWidth";
            case 8:
                return "getHeight";
            case 9:
                return "drawString";
            case 10:
                return "addSliderSetting";
            case 11:
                return "addBooleanSetting";
            case 12:
                return "addListSetting";
            case 13:
                return "hook";
            case 14:
                return "toggle";
            case 15:
                return "sendPacket";
            case 16:
                return "sendPacketNoEvent";
            case 17:
                return "sendPacketNoEventDelayed";
            case 18:
                return "addToSendQueue";
            case 19:
                return "getX";
            case 20:
                return "getY";
            case 21:
                return "getZ";
            case 22:
                return "setX";
            case 23:
                return "setY";
            case 24:
                return "setZ";
            case 25:
                return "setPos";
            case 26:
                return "getMotionX";
            case 27:
                return "getMotionY";
            case 28:
                return "getMotionZ";
            case 29:
                return "setMotionX";
            case 30:
                return "setMotionY";
            case 31:
                return "setMotionZ";
            case 32:
                return "getHurtTime";
            case 33:
                return "isOnGround";
            case 34:
                return "setOnGround";
            case 35:
                return "isSprinting";
            case 36:
                return "setSprinting";
            case 37:
                return "isSneaking";
            case 38:
                return "setSneaking";
            case 39:
                return "getRotationYaw";
            case 40:
                return "setRotationYaw";
            case 41:
                return "getRotationPitch";
            case 42:
                return "setRotationPitch";
            case 43:
                return "getHealth";
            case 44:
                return "jump";
            case 45:
                return "registerModule";
            case 46:
                return "registerHudElement";
            case 47:
                return "getScript";
            case 48:
                return "getEntity";
            default:
                return getString2(input);
        }
    }

    private static String getString2(int input) {
        switch (input) {
            case 49:
                return "isPreAttack";
            case 50:
                return "getMessage";
            case 51:
                return "setMessage";
            case 52:
                return "setPosX";
            case 53:
                return "setPosY";
            case 54:
                return "setPosZ";
            case 55:
                return "getBoundingBox";
            case 56:
                return "setBoundingBox";
            case 57:
                return "getBlock";
            case 58:
                return "getState";
            case 59:
                return "getAttacker";
            case 60:
                return "getUpwardsMotion";
            case 61:
                return "setUpwardsMotion";
            case 62:
                return "getKey";
            case 63:
                return "getButton";
            case 64:
                return "getYaw";
            case 65:
                return "getPitch";
            case 66:
                return "setYaw";
            case 67:
                return "setPitch";
            case 68:
                return "getPacket";
            case 69:
                return "getStrafeMultiplier";
            case 70:
                return "setStrafeMultiplier";
            case 71:
                return "getForwardMultiplier";
            case 72:
                return "setForwardMultiplier";
            case 73:
                return "getStepHeight";
            case 74:
                return "setStepHeight";
            case 75:
                return "getResponse";
            case 76:
                return "message";
            case 77:
                return "isMoving";
            case 78:
                return "shouldMove";
            case 79:
                return "getSpeed";
            case 80:
                return "getBaseMoveSpeed";
            case 81:
                return "strafe";
            case 82:
                return "stop";
            case 83:
                return "stopHoriz";
            case 84:
                return "setSpeed";
            case 85:
                return "getDirection";
            case 86:
                return "drawRect";
            case 87:
                return "drawHollowRect";
            default:
                return getString3(input);
        }
    }

    private static String getString3(int input) {
        switch (input) {
            case 88:
                return "onEnable";
            case 89:
                return "onDisable";
            case 90:
                return "EventRender2D";
            case 91:
                return "EventRender3D";
            case 92:
                return "EventChatOutput";
            case 93:
                return "EventCollide";
            case 94:
                return "EventDeath";
            case 95:
                return "EventJump";
            case 96:
                return "EventKey";
            case 97:
                return "EventMouseClick";
            case 98:
                return "EventMouse";
            case 99:
                return "EventMove";
            case 100:
                return "EventPostMotion";
            case 101:
                return "EventPreMotion";
            case 102:
                return "EventReceivePacket";
            case 103:
                return "EventSendPacket";
            case 104:
                return "EventSlowdown";
            case 105:
                return "EventStep";
            case 106:
                return "EventTeleport";
            case 107:
                return "EventUpdate";
            case 108:
                return "EventWorldChange";
            case 109:
                return "EventAttack";
            case 110:
                return "EventConnection";
            case 111:
                return "ChatUtils";
            case 112:
                return "getValue";
            case 113:
                return "setValue";
            case 114:
                return "getOptions";
            case 115:
                return "getDefaultValue";
            case 116:
                return "getMin";
            case 117:
                return "getMax";
            case 118:
                return "onlyInt";
            case 119:
                return "getValueF";
            case 120:
                return "getValueL";
            case 121:
                return "getValueI";
            case 122:
                return "getIncrement";
            default:
                return "skidder";
        }
    }

}
